POST http://localhost:5000/api/user/join
Content-Type: application/json; charset=utf-8

{
    "id": "TEST",
    "password": "TEST33",
    "serial": "TEST1234"
}

POST http://localhost:5000/api/user/login
Content-Type: application/json; charset=utf-8

{
    "id": "TEST",
    "password": "TEST33"
}

GET http://localhost:5000/api/arduino/save?data={temp:30,humidity:30,flame:300,rain:20,vibe:30}&serial=TEST1234

GET http://localhost:5000/api/arduino/get


POST http://211.253.229.117:5000/api/user/join
Content-Type: application/json; charset=utf-8

{
    "id": "TEST",
    "password": "TEST33",
    "serial": "TEST1234"
}

POST http://211.253.229.117:5000/api/user/login
Content-Type: application/json; charset=utf-8
{
    "id": "TEST",
    "password": "TEST33"
}